### ISSUE TITLE
Reduce memory usage

### ISSUE THREAD

**Issue by SimonMarechal** [synacktiv/rulesfinder#3]
It is not clear if that is possible in a meaningful way. There are a few memory hogs:

# Cleartext hashmap

This is:
```rust
HashMap<Vec<u8>, Vec<(Vec<u8>, Vec<u8>, u64)>>
```

All of these `Vec<u8>` are really short, so a more compact storage format could save a lot. Maybe a custom type that either stores 7 bytes or a pointer would be sufficient? Alternatively, we could just use `u64` and reject everything larger than 8 characters.

Alternatively again, maybe a hashmap is not the best structure here. Perhaps some sort of trie would be more efficient. Experiences with the C version of this tool showed that rolling hashes could give good performance too.

# Rules sets

This is:
```rust
HashMap<Vec<rules::Rule>, BTreeSet<u64>>
```

The `Vec<rules::Rules>` thing is perhaps not the best thing for a key, but the culprit is most likely the `BTreeSet`.

**Comment by 0xVavaldi** [comment]
Another item of interest is calculating the estimated memory usage and informing the user. I'd like to perform a larger analysis but even with 128GB of RAM the program kills itself without informing me why or hitting the storage limit. It just silently quits.

Now I know the sizes I'm playing around with are large, but if I were to rent an EC2 instance with a lot more memory I'd like to at least know if it COULD complete the analysis or not.
