### ISSUE TITLE
Rules display bug

### ISSUE THREAD

**Issue by SimonMarechal** [synacktiv/rulesfinder#8]
Right now, invalid rules can be displayed because the printer has no idea which mode it is in.

Code must be modified so that the printer knows its mode (JtR, JtRHashcatLogic, Hashcat), and return a optional result.

**Comment by n0kovo** [comment]
Did you ever work out a solution to this?

**Comment by SimonMarechal** [comment]
Yes I did, but from your other issue it is apparent something is still wrong!
